### PR TITLE
Fix #4 by appropriately converting nothing to missing for data tables

### LINKED ISSUE #4: Problem with missing/nothing and copying
It is best shown on an example
```
julia> using DataFrames, JSONTables

julia> x = DataFrame(A=[true, false, true], B=[1, 2, missing],
                     C=[missing, "b", "c"], D=['a', missing, 'c'])
3×4 DataFrame
│ Row │ A     │ B       │ C       │ D       │
│     │ Bool  │ Int64⍰  │ String⍰ │ Char⍰   │
├─────┼───────┼─────────┼─────────┼─────────┤
│ 1   │ true  │ 1       │ missing │ 'a'     │
│ 2   │ false │ 2       │ b       │ missing │
│ 3   │ true  │ missing │ c       │ 'c'     │

julia> s1 = arraytable(x)
"[{\"A\":true,\"B\":1,\"C\":null,\"D\":\"a\"},{\"A\":false,\"B\":2,\"C\":\"b\",\"D\":null},{\"A\":true,\"B\":null,\"C\":\"c\",\"D\":\"c\"}]"

julia> s2 = objecttable(x)
"{\"A\":[true,false,true],\"B\":[1,2,null],\"C\":[null,\"b\",\"c\"],\"D\":[\"a\",null,\"c\"]}"

julia> j1 = jsontable(s1)
JSONTables.Table{false,JSON3.Array{JSON3.Object,Base.CodeUnits{UInt8,String},Array{UInt64,1}}}(JSON3.Object[{
   "A": true,
   "B": 1,
   "C": nothing,
   "D": "a"
}, {
   "A": false,
   "B": 2,
   "C": "b",
   "D": nothing
}, {
   "A": true,
   "B": nothing,
   "C": "c",
   "D": "c"
}])

julia> j2 = jsontable(s2)
JSONTables.Table{true,JSON3.Object{Base.CodeUnits{UInt8,String},Array{UInt64,1}}}({
   "A": [
          true,
          false,
          true
        ],
   "B": [
          1,
          2,
          nothing
        ],
   "C": [
          nothing,
          "b",
          "c"
        ],
   "D": [
          "a",
          nothing,
          "c"
        ]
})

julia> DataFrame(j1)
3×4 DataFrame
│ Row │ A     │ B      │ C      │ D      │
│     │ Bool  │ Union… │ Union… │ Union… │
├─────┼───────┼────────┼────────┼────────┤
│ 1   │ true  │ 1      │        │ a      │
│ 2   │ false │ 2      │ b      │        │
│ 3   │ true  │        │ c      │ c      │

julia> DataFrame(j2)
ERROR: MethodError: no method matching copy(::Nothing)
```

And there are two issues:
1. `missing` gets converted to `nothing` in the write-read back process
2. later you cannot materialize it with `DataFrame` constructor as internally a copy of the read-in vector is attempted and it fails as it contains `nothing` - but only in `objecttable` case

CC @quinnj

### PR DESCRIPTION
**Pull request by quinnj**
@bkamins, if you can try this PR out on your use-case that'd be great.

### CODE REVIEW

**Comment by bkamins** [comment]
Thank you for the fix. There are the following problems (using the variables from my issue https://github.com/JuliaData/JSONTables.jl/issues/4):

`DataFrame(j2)` fails due to:
```
julia> DataFrame(j2)
ERROR: MethodError: no method matching copy(::Missing)
```

Also there are the following additional issues that `Tables.rows` and `Tables.columns` seem to retain `nothing`, e.g.:
```
julia> collect(Tables.rows(j1))
3-element Array{Any,1}:
 JSONTables.MissingRow{JSON3.Object{Base.CodeUnits{UInt8,String},SubArray{UInt64,1,Array{UInt64,1},Tuple{UnitRange{Int64}},true}}}({
   "A": true,
   "B": 1,
   "C": nothing,
   "D": "a"
})
 JSONTables.MissingRow{JSON3.Object{Base.CodeUnits{UInt8,String},SubArray{UInt64,1,Array{UInt64,1},Tuple{UnitRange{Int64}},true}}}({
   "A": false,
   "B": 2,
   "C": "b",
   "D": nothing
})
 JSONTables.MissingRow{JSON3.Object{Base.CodeUnits{UInt8,String},SubArray{UInt64,1,Array{UInt64,1},Tuple{UnitRange{Int64}},true}}}({
   "A": true,
   "B": nothing,
   "C": "c",
   "D": "c"
})
```
(but this might be only a printing issue, as accessing the fields correctly changes `nothing` to `missing`)

**Comment by bkamins** [comment]
`Tables.rowtable` and `Tables.columntable` work OK both for `j1` and `j2`.

**Comment by quinnj** [comment]
Ah, thanks for looking at this @bkamins; I forgot to test the `DataFrame(x)` case. It should be working now; it actually uncovered the same bug in JSON3, which is that `copy(missing)` and `copy("hey")` are both MethodErrors. I've pushed a fix to JSON3.jl and applied the same logic here (this doesn't depend on the fix being in JSON3, it just employs the same fix logic).

As you noted, the row case is just a display issue.

**Comment by bkamins** [comment]
Actually maybe a PR to Base adding `copy` for `Missing` and `AbstractString` could be in place? What do you think?

**Pull request merged**
